# 5.2 基本功能

In [22]:
import pandas as pd
import numpy as np
obj = pd.Series([4.5,7.2,-5.3,3.6], index=['a','b','c','d'])
obj2 = obj.reindex(['d','c','b','a'])
obj2

d    3.6
c   -5.3
b    7.2
a    4.5
dtype: float64

In [23]:
odj3 = pd.Series(['Blue','purple','yellow'],index=[0,2,4])
odj3.reindex(np.arange(6),method='ffill')  # 前向填充

0      Blue
1      Blue
2    purple
3    purple
4    yellow
5    yellow
dtype: str

In [24]:
# 还可以用loc重建索引
frame = pd.DataFrame(np.arange(9).reshape((3,3)),index=['a','c','d'],columns=['Ohio','Texas','California'])
print(frame.loc[['a','c','d'],['California','Texas']])

   California  Texas
a           2      1
c           5      4
d           8      7

In [25]:
print(frame.drop(['d','a']))  # 行列都可以删

   Ohio  Texas  California
c     3      4           5

In [26]:
# loc切片是包括后端的
# 数据选取用iloc和loc最好 可以同之前列表出现-1等等 (.iloc[-1])
# loc可以使用bool型数组
data = pd.DataFrame([[1,0,0,0],[1,5,6,7],[8,9,10,11],[1,13,14,15]],columns=['one','two','three','four'],index=['ohio','colorado','utah','new'])
print(data)

          one  two  three  four
ohio        1    0      0     0
colorado    1    5      6     7
utah        8    9     10    11
new         1   13     14    15

In [27]:
data.loc[data['three']>3,'three'] = 6
print(data)

          one  two  three  four
ohio        1    0      0     0
colorado    1    5      6     7
utah        8    9      6    11
new         1   13      6    15

In [28]:
# df1.add(df2,fill_value=0)   # df1和df2相加，缺失值用0填充
df1 = pd.DataFrame(np.random.rand(4,3),columns=list('bde'),index=['Utah','Ohio','Texas','Oregon'])
np.abs(df1)

               b         d         e
Utah    0.239635  0.377043  0.866463
Ohio    0.879027  0.931152  0.679510
Texas   0.804180  0.288389  0.955201
Oregon  0.692972  0.385455  0.847318

In [29]:
df1.apply(lambda x: x.max()-x.min())

b    0.639392
d    0.642764
e    0.275690
dtype: float64

In [30]:
df1.apply(lambda x: x.max()-x.min(),axis=1)

Utah      0.626828
Ohio      0.251642
Texas     0.666812
Oregon    0.461862
dtype: float64

In [31]:
def f(x):
    return pd.Series([x.min(),x.max()],index=['min','max'])
df1.apply(f)

            b         d         e
min  0.239635  0.288389  0.679510
max  0.879027  0.931152  0.955201

In [33]:
df1.map(lambda x: round(x, 2))

           b     d     e
Utah    0.24  0.38  0.87
Ohio    0.88  0.93  0.68
Texas   0.80  0.29  0.96
Oregon  0.69  0.39  0.85

In [34]:
frame = pd.DataFrame(np.arange(8).reshape(2,4),index=['three','one'],columns=['d','a','b','c'])
frame.sort_index()

       d  a  b  c
one    4  5  6  7
three  0  1  2  3

In [35]:
frame.sort_index(axis='columns')

       a  b  c  d
three  1  2  3  0
one    5  6  7  4

In [36]:
# 降序 ascending=False
obj = pd.Series([4,7,-3,2,np.nan])
obj.sort_values(na_position='first')

4    NaN
2   -3.0
3    2.0
0    4.0
1    7.0
dtype: float64

In [38]:
frame = pd.DataFrame({'b':[4,7,-3,2],'a':[0,1,0,1]})
frame.sort_values('b')

   b  a
2 -3  0
3  2  1
0  4  0
1  7  1

In [42]:
frame.sort_values(['a','b'])

   b  a
2 -3  0
0  4  0
3  2  1
1  7  1

In [43]:
obj = pd.Series([7,-5,7,4,2,0,4])
obj.rank()

0    6.5
1    1.0
2    6.5
3    4.5
4    3.0
5    2.0
6    4.5
dtype: float64

In [ ]:
# is_unique方法可以判断索引是否唯一

# End