# 5.3 描述性统计的汇总和计算

In [2]:
import pandas as pd
import numpy as np
df = pd.DataFrame([[1.4,np.nan],[7.1,-4.5],[np.nan,np.nan],[0.75,-1.3]],index=['a','b','c','d'],columns=['one','two'])
print(df)

    one  two
a  1.40  NaN
b  7.10 -4.5
c   NaN  NaN
d  0.75 -1.3

In [3]:
print(df.sum())

one    9.25
two   -5.80
dtype: float64

In [4]:
df.sum(axis=1)

a    1.40
b    2.60
c    0.00
d   -0.55
dtype: float64

In [5]:
df.sum(axis=0,skipna=False)

one   NaN
two   NaN
dtype: float64

In [6]:
df.mean(axis=1)

a    1.400
b    1.300
c      NaN
d   -0.275
dtype: float64

In [7]:
# 最小值和最大值的索引
df.idxmax()

one    b
two    d
dtype: str

In [8]:
df.idxmin()

one    d
two    b
dtype: str

In [9]:
df.cumsum()

    one  two
a  1.40  NaN
b  8.50 -4.5
c   NaN  NaN
d  9.25 -5.8

In [11]:
df1 = pd.DataFrame([[1.4,2.4],[7.1,4.5],[8.9,7.3],[0.75,1.3]],index=['a','b','c','d'],columns=['one','two'])
df1.pct_change()

        one       two
a       NaN       NaN
b  4.071429  0.875000
c  0.253521  0.622222
d -0.915730 -0.821918

In [12]:
df1['one'].corr(df1['two'])   # 相关系数

np.float64(0.9580232401992469)

In [13]:
df1['one'].cov(df1['two'])   # 协方差

np.float64(10.307916666666667)

In [14]:
df1.corr()

          one       two
one  1.000000  0.958023
two  0.958023  1.000000

In [15]:
df.cov()

           one    two
one  12.205833 -10.16
two -10.160000   5.12

In [16]:
# corrwith方法可以计算一个dataframe中列或行与另一个Series或DataFrame的列或行之间的相关系数
df1.corrwith(df['one'])

one    1.000000
two    0.968431
dtype: float64

In [18]:
obj = pd.Series(['c','a','d','a','a','b','b','c','c','c'])
uniques = obj.unique()
uniques

<StringArray>
['c', 'a', 'd', 'b']
Length: 4, dtype: str

In [19]:
obj.value_counts()

c    4
a    3
b    2
d    1
Name: count, dtype: int64

In [22]:
mask = obj.isin(['b','c'])
obj[mask]

0    c
5    b
6    b
7    c
8    c
9    c
dtype: str

In [23]:
to_match = pd.Series(['c','a','b','b','c','a'])
unique_vals = pd.Series(['c','b','a'])
indices = pd.Index(unique_vals).get_indexer(to_match)
indices

array([0, 2, 1, 1, 0, 2])

In [24]:
data = pd.DataFrame({'Q1':[1,3,4,3,4],'Q2':[2,3,1,2,3],'Q3':[1,5,2,4,4]})
data

   Q1  Q2  Q3
0   1   2   1
1   3   3   5
2   4   1   2
3   3   2   4
4   4   3   4

In [25]:
data['Q1'].value_counts().sort_index()

Q1
1    1
3    2
4    2
Name: count, dtype: int64

In [28]:
result = data.apply(lambda x: x.value_counts()).fillna(0)
result

    Q1   Q2   Q3
1  1.0  1.0  1.0
2  0.0  2.0  1.0
3  2.0  2.0  0.0
4  2.0  0.0  2.0
5  0.0  0.0  1.0

# End